### ISSUE TITLE
Read the updated conditions for idle instance

### ISSUE THREAD

**Issue by waheedullahkhan001** [Codycody31/Prevent-OCI-Deletion-for-being-idle#26]
https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm#compute__idleinstances

## Reclamation of Idle Compute Instances

Idle Always Free compute instances may be reclaimed by Oracle. Oracle will deem virtual machine and bare metal compute instances as idle if, during a 7-day period, the following are true:

- CPU utilization for the 95th percentile is less than 20%
- Network utilization is less than 20%
- Memory utilization is less than 20% (applies to [A1 shapes](https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm#Details_of_the_Always_Free_Compute_instance__a1_flex) only)

**Comment by Codycody31** [comment]
Thanks for pointing that out. Just bout to merge in an update for the README.md
